image: docker

services:
  - docker:dind

before_script:
  - apt-get update -qq &&
    apt-get install curl

  # Install docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose &&
    chmod +x /usr/local/bin/docker-compose

  # Setup the KinD cluster
  - docker-compose up -d

  # Install kubectl
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl &&
    chmod +x kubectl &&
    mv kubectl /usr/local/bin/

test:
  script:
    - export KUBECONFIG="$(pwd)/tmp/kube/config"
    - kubectl cluster-info
    - kubectl get pods --all-namespaces
