image: docker

services:
  - docker:dind

before_script:
  - apk update &&
    apk add curl py-pip

  # Install docker-compose
  - pip install docker-compose

  # Setup the KinD cluster
  - docker-compose up -d

  # Install kubectl
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl &&
    chmod +x kubectl &&
    mv kubectl /usr/local/bin/

test:
  script:
    - export KUBECONFIG="$(pwd)/tmp/kube/config"
    - kubectl cluster-info
    - kubectl get pods --all-namespaces
