image: docker

services:
  - docker:dind

before_script:
  - apk add curl

  # Install docker-compose
  - curl -Lo docker-compose https://github.com/docker/compose/releases/download/1.18.0/docker-compose-$(uname -s)-$(uname -m) &&
    chmod +x docker-compose &&
    sh docker-compose version &&
    mv docker-compose /usr/local/bin/

  # Setup the KinD cluster
  - docker-compose up -d

  # Install kubectl
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl &&
    chmod +x kubectl &&
    mv kubectl /usr/local/bin/

test:
  script:
    - export KUBECONFIG="$(pwd)/tmp/kube/config"
    - kubectl cluster-info
    - kubectl get pods --all-namespaces
