services:
  - docker:dind

before_script:
  # Install Docker Client
  - DOCKER_VERSION="17.03.0-ce" &&
    curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_VERSION.tgz &&
    tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz &&
    mv /tmp/docker/* /usr/bin
  - export DOCKER_HOST=tcp://docker:2375 &&
    docker version

  # Install KinD
  # - curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/0.1.0/kind-linux-amd64 &&
  #   chmod +x kind &&
  #   mv kind /usr/local/bin/
  - curl -O https://storage.googleapis.com/golang/go1.11.2.linux-amd64.tar.gz &&
    tar -xf go1.11.2.linux-amd64.tar.gz &&
    mv go /usr/local &&
    export GOPATH=$HOME/go &&
    export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
  - go get -u sigs.k8s.io/kind &&
    cd $GOPATH/src/sigs.k8s.io/kind &&
    git remote add snormore https://github.com/snormore/kind.git &&
    git fetch snormore net-host &&
    git checkout snormore/net-host &&
    go build -o $GOPATH/bin/kind
  
  # Create Kubernetes Cluster
  - kind create cluster --loglevel debug
  #  --retain
  # - kind export logs logs && 
  #   cat logs/docker-info.txt &&
  #   tail logs/kind-control-plane/kubelet.log
  
  # Install kubectl
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl &&
    chmod +x kubectl &&
    mv kubectl /usr/local/bin/

test:
  script:
    - export KUBECONFIG="$(kind get kubeconfig-path)"
    - kubectl cluster-info
    - kubectl get pods --all-namespaces
