version: '3'
services:
  kind:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./tmp/kube:/root/.kube
    # environment:
    #   DOCKER_HOST: "tcp://docker:2375"
    network_mode: host