version: 2
jobs:
  build:
    working_directory: /go/src/github.com/snormore/kind-circleci
    docker:
      - image: golang:1.11
    environment:
      DEP_VERSION: 0.4.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker Client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Setup KinD cluster.
          command: |
            go get github.com/kubernetes-sigs/kind
            kind create cluster --name="1"
            export KUBECONFIG="$(kind get kubeconfig-path --name="1")"
      - run:
          name: Run Tests
          command: go run main.go
      - run:
          name: Build
          command: go build